"""SPEC.md resolution and generation for the discovery pipeline."""

from __future__ import annotations

import json
from pathlib import Path

import structlog

from factory.models import ProjectProfile

log = structlog.get_logger()

_EXCLUDE_DIRS = {
    "tests", "test", ".venv", "venv", "node_modules", "__pycache__",
    ".git", ".factory", "eval", "dist", "build", ".mypy_cache",
    ".tox", ".eggs", ".pytest_cache",
}


def resolve_spec(project_path: Path) -> tuple[Path | None, str]:
    """Locate an existing SPEC.md — committed (project root) takes priority over generated (.factory/)."""
    committed = project_path / "SPEC.md"
    if committed.exists():
        log.debug("resolve_spec", source="committed", path=str(committed))
        return committed, "committed"

    generated = project_path / ".factory" / "SPEC.md"
    if generated.exists():
        log.debug("resolve_spec", source="generated", path=str(generated))
        return generated, "generated"

    log.debug("resolve_spec", source="absent")
    return None, "absent"


def generate_spec(project_path: Path, profile: ProjectProfile) -> str:
    """Produce a SPEC.md document from discovered project data."""
    sections: list[str] = []

    sections.append(f"# {profile.name} Specification")
    sections.append("")
    sections.append("Status: Auto-generated by re:factory discovery")
    sections.append("")
    sections.append("## Normative Language")
    sections.append(
        "The key words MUST, MUST NOT, REQUIRED, SHOULD, SHOULD NOT, RECOMMENDED, "
        "MAY, and OPTIONAL in this document are to be interpreted as described in RFC 2119."
    )

    # Section 1: Project Identity
    sections.append("")
    sections.append("## 1. Project Identity")
    sections.append(f"- **Name:** {profile.name}")
    sections.append(f"- **Type:** {profile.project_type}")
    sections.append(f"- **Language:** {profile.language}")
    sections.append(f"- **Framework:** {profile.framework or 'None detected'}")
    sections.append(f"- **Package Manager:** {profile.package_manager or 'None detected'}")

    # Section 2: Goals
    sections.append("")
    sections.append("## 2. Goals")
    readme_summary = _read_readme_summary(project_path)
    sections.append(readme_summary)

    # Section 3: Technical Stack
    sections.append("")
    sections.append("## 3. Technical Stack")
    sections.append("### 3.1 Dependencies")
    deps = _read_top_level_deps(project_path, profile.language)
    if deps:
        for dep in deps:
            sections.append(f"- {dep}")
    else:
        sections.append("No dependencies detected.")
    sections.append("")
    sections.append("### 3.2 Development Tools")
    sections.append(f"- **Test command:** {profile.test_command or 'Not configured'}")
    sections.append(f"- **Lint command:** {profile.lint_command or 'Not configured'}")
    sections.append(
        f"- **Type check command:** {profile.type_check_command or 'Not configured'}"
    )
    sections.append(f"- **CI:** {'Configured' if profile.has_ci else 'Not configured'}")

    # Section 4: Architecture
    sections.append("")
    sections.append("## 4. Architecture")
    source_dirs = _detect_source_dirs(project_path, profile.language)
    if source_dirs:
        for d in source_dirs:
            sections.append(f"- `{d}/`")
    else:
        sections.append("No source directories detected.")

    # Section 5: Eval Dimensions
    sections.append("")
    sections.append("## 5. Eval Dimensions")
    eval_profile_path = project_path / ".factory" / "eval_profile.json"
    if eval_profile_path.exists():
        try:
            ep = json.loads(eval_profile_path.read_text())
            dims = ep.get("dimensions", [])
            if dims:
                for dim in dims:
                    name = dim.get("name", "unknown")
                    weight = dim.get("weight", 0)
                    source = dim.get("source", "unknown")
                    sections.append(f"- **{name}** (weight: {weight}, source: {source})")
            else:
                sections.append("No eval dimensions configured.")
        except (json.JSONDecodeError, OSError):
            sections.append("Run `factory discover` to generate eval dimensions.")
    else:
        sections.append("Run `factory discover` to generate eval dimensions.")

    # Section 6: Known Issues
    sections.append("")
    sections.append("## 6. Known Issues")
    issues = _fetch_github_issues(project_path)
    if issues:
        for issue in issues[:10]:
            sections.append(f"- **#{issue['number']}** {issue['title']}")
    else:
        sections.append("No issues data available.")

    # Section 7: Backlog
    sections.append("")
    sections.append("## 7. Backlog")
    backlog_path = project_path / ".factory" / "strategy" / "backlog.md"
    if backlog_path.exists():
        try:
            content = backlog_path.read_text().strip()
            if content:
                items = [
                    line.lstrip("- ").strip()
                    for line in content.splitlines()
                    if line.strip() and not line.strip().startswith("#")
                ]
                if items:
                    for item in items:
                        sections.append(f"- {item}")
                else:
                    sections.append("No backlog items.")
            else:
                sections.append("No backlog items.")
        except OSError:
            sections.append("No backlog items.")
    else:
        sections.append("No backlog items.")

    sections.append("")
    return "\n".join(sections)


def _read_readme_summary(project_path: Path) -> str:
    """Read README.md and return the first non-heading, non-empty paragraph."""
    for name in ("README.md", "README.rst", "README.txt", "README"):
        readme_path = project_path / name
        if readme_path.exists():
            try:
                text = readme_path.read_text()
            except OSError:
                continue
            for line in text.splitlines():
                stripped = line.strip()
                if not stripped:
                    continue
                if stripped.startswith("#"):
                    continue
                if stripped.startswith("===") or stripped.startswith("---"):
                    continue
                return stripped
    return "Goals not yet documented."


def _detect_source_dirs(project_path: Path, language: str) -> list[str]:
    """Find source directories based on language conventions."""
    dirs: list[str] = []
    if language == "python":
        for d in sorted(project_path.iterdir()):
            if not d.is_dir() or d.name in _EXCLUDE_DIRS or d.name.startswith("."):
                continue
            if (d / "__init__.py").exists():
                dirs.append(d.name)
    elif language in ("typescript", "javascript"):
        src = project_path / "src"
        if src.is_dir():
            dirs.append("src")
        lib = project_path / "lib"
        if lib.is_dir():
            dirs.append("lib")
    elif language == "go":
        for d in sorted(project_path.iterdir()):
            if not d.is_dir() or d.name in _EXCLUDE_DIRS or d.name.startswith("."):
                continue
            if any(d.glob("*.go")):
                dirs.append(d.name)
    elif language == "rust":
        src = project_path / "src"
        if src.is_dir():
            dirs.append("src")
    return dirs


def _read_top_level_deps(project_path: Path, language: str) -> list[str]:
    """Parse top-level dependency names from project config files."""
    deps: list[str] = []
    if language == "python":
        pyproject = project_path / "pyproject.toml"
        if pyproject.exists():
            try:
                text = pyproject.read_text()
                in_deps = False
                for line in text.splitlines():
                    stripped = line.strip()
                    if stripped == "dependencies = [":
                        in_deps = True
                        continue
                    if in_deps:
                        if stripped == "]":
                            break
                        name = stripped.strip('",').split(">=")[0].split("==")[0].split(
                            "<"
                        )[0].split(">")[0].split("[")[0].strip()
                        if name:
                            deps.append(name)
            except OSError:
                pass
    elif language in ("typescript", "javascript"):
        pkg_path = project_path / "package.json"
        if pkg_path.exists():
            try:
                pkg = json.loads(pkg_path.read_text())
                for name in sorted(pkg.get("dependencies", {}).keys()):
                    deps.append(name)
            except (json.JSONDecodeError, OSError):
                pass
    return deps


def _fetch_github_issues(project_path: Path) -> list[dict[str, str | int]]:
    """Fetch open GitHub issues via gh CLI. Returns empty list on failure."""
    import subprocess

    try:
        result = subprocess.run(
            ["gh", "issue", "list", "--state", "open", "--limit", "10", "--json",
             "number,title"],
            capture_output=True, text=True, timeout=10,
            cwd=project_path,
        )
        if result.returncode == 0 and result.stdout.strip():
            return json.loads(result.stdout)
    except (subprocess.TimeoutExpired, FileNotFoundError, json.JSONDecodeError, OSError):
        pass
    return []
