#!/usr/bin/env bash
set -euo pipefail

# check-component-import.sh
# -------------------------
# Ensures feature code uses the project's component library instead of
# reaching for raw primitive-library imports or native HTML elements.
#
# Rules are derived from .factory/design-system/design-baseline.json
# (generated by the auditor agent at runtime). If the baseline does not
# exist, the check exits neutral (score 1.0, exit 0).
#
# Reads from the baseline:
#   - component_inventory.component_library_dir (e.g., "src/components/ui")
#   - component_inventory.primitive_library (e.g., "@radix-ui", "@mui", "@chakra-ui")
#
# Catches in changed .tsx files (excluding the component library dir):
#   a) Direct imports from the primitive library
#   b) Raw HTML interactive elements: <button, <input, <select, <table,
#      <textarea, <checkbox (lowercase tags = HTML, not React components)
#
# Exit 0 = pass, Exit 1 = fail
# Use --score to get JSON output for eval integration.

SCORE_MODE=false
if [[ "${1:-}" == "--score" ]]; then
  SCORE_MODE=true
fi

BASELINE=".factory/design-system/design-baseline.json"

# --- Load baseline or exit neutral ---
if [[ ! -f "$BASELINE" ]]; then
  if $SCORE_MODE; then
    echo '{"score": 1.0, "details": "No design-baseline.json found. Skipping component import check (neutral)."}'
  else
    echo "NEUTRAL: No design-baseline.json found. Skipping component import check."
  fi
  exit 0
fi

# --- Extract configuration from baseline ---
# component_library_dir: the path to the project's UI component wrappers
COMPONENT_LIB_DIR=$(grep -oE '"component_library_dir"\s*:\s*"[^"]*"' "$BASELINE" 2>/dev/null \
  | sed -E 's/"component_library_dir"\s*:\s*"//;s/"$//' || true)

# primitive_library: the underlying primitive library (e.g., @radix-ui, @mui)
PRIMITIVE_LIB=$(grep -oE '"primitive_library"\s*:\s*"[^"]*"' "$BASELINE" 2>/dev/null \
  | sed -E 's/"primitive_library"\s*:\s*"//;s/"$//' || true)

# If neither is configured, nothing to check
if [[ -z "$COMPONENT_LIB_DIR" ]] && [[ -z "$PRIMITIVE_LIB" ]]; then
  if $SCORE_MODE; then
    echo '{"score": 1.0, "details": "No component library config in baseline. Skipping (neutral)."}'
  else
    echo "NEUTRAL: No component library configuration in design-baseline.json. Skipping."
  fi
  exit 0
fi

# --- Gather files to check, excluding the component library dir ---
EXCLUDE_PATTERN=""
if [[ -n "$COMPONENT_LIB_DIR" ]]; then
  EXCLUDE_PATTERN="$COMPONENT_LIB_DIR/"
fi

if [[ "${SCAN_MODE:-}" == "full" ]]; then
  ALL_TSX=$(find "${SCAN_SRC_DIR:-src}" -type f -name '*.tsx' 2>/dev/null | sort || true)
  if [[ -n "$EXCLUDE_PATTERN" ]]; then
    CHANGED_TSX=$(echo "$ALL_TSX" | grep -v "$EXCLUDE_PATTERN" || true)
  else
    CHANGED_TSX="$ALL_TSX"
  fi
else
  CHANGED_FILES=$(git diff --name-only HEAD~1 2>/dev/null || true)
  if [[ -n "$EXCLUDE_PATTERN" ]]; then
    CHANGED_TSX=$(echo "$CHANGED_FILES" | grep -E '\.tsx$' | grep -v "$EXCLUDE_PATTERN" || true)
  else
    CHANGED_TSX=$(echo "$CHANGED_FILES" | grep -E '\.tsx$' || true)
  fi
fi

if [[ -z "$CHANGED_TSX" ]]; then
  if $SCORE_MODE; then
    echo '{"score": 1.0, "details": "No changed .tsx files outside component library to check."}'
  else
    echo "PASS: No changed .tsx files outside the component library to check."
  fi
  exit 0
fi

VIOLATIONS=""
VIOLATION_COUNT=0
TOTAL_INTERACTIVE=0

# Raw HTML elements that should be wrapped components
RAW_ELEMENTS="button|input|select|table|textarea|checkbox"

while IFS= read -r file; do
  [[ -z "$file" ]] && continue
  [[ ! -f "$file" ]] && continue

  LINE_NUM=0
  while IFS= read -r line; do
    LINE_NUM=$((LINE_NUM + 1))

    # Check (a): Direct primitive library imports (only if primitive_library is set)
    if [[ -n "$PRIMITIVE_LIB" ]]; then
      if echo "$line" | grep -qE "from ['\"]${PRIMITIVE_LIB}"; then
        VIOLATION_COUNT=$((VIOLATION_COUNT + 1))
        TOTAL_INTERACTIVE=$((TOTAL_INTERACTIVE + 1))
        LIB_DIR_MSG=""
        if [[ -n "$COMPONENT_LIB_DIR" ]]; then
          LIB_DIR_MSG=" (use a wrapper from ${COMPONENT_LIB_DIR}/ instead)"
        fi
        VIOLATIONS="${VIOLATIONS}  ${file}:${LINE_NUM}  Direct ${PRIMITIVE_LIB} import${LIB_DIR_MSG}\n"
        VIOLATIONS="${VIOLATIONS}    ${line}\n"
        continue
      fi
    fi

    # Check (b): Raw HTML interactive elements (lowercase tag names in JSX)
    # Match opening tags like <button, <input, etc. but not <Button, <Input
    RAW_MATCHES=$(echo "$line" | grep -oE "<(${RAW_ELEMENTS})([[:space:]>\/])" 2>/dev/null || true)
    if [[ -n "$RAW_MATCHES" ]]; then
      while IFS= read -r match; do
        [[ -z "$match" ]] && continue
        ELEMENT=$(echo "$match" | sed -E 's/<([a-z]+).*/\1/')
        VIOLATION_COUNT=$((VIOLATION_COUNT + 1))
        TOTAL_INTERACTIVE=$((TOTAL_INTERACTIVE + 1))
        VIOLATIONS="${VIOLATIONS}  ${file}:${LINE_NUM}  Raw <${ELEMENT}> element (use the design system component instead)\n"
      done <<< "$RAW_MATCHES"
    fi

    # Count all interactive elements (including proper component usage) for scoring
    # Look for PascalCase versions too: <Button, <Input, <Select, etc.
    COMPONENT_MATCHES=$(echo "$line" | grep -oE "<(Button|Input|Select|Table|Textarea|Checkbox)([[:space:]>\/])" 2>/dev/null || true)
    if [[ -n "$COMPONENT_MATCHES" ]]; then
      COMPONENT_COUNT=$(echo "$COMPONENT_MATCHES" | wc -l | tr -d ' ')
      TOTAL_INTERACTIVE=$((TOTAL_INTERACTIVE + COMPONENT_COUNT))
    fi
  done < "$file"
done <<< "$CHANGED_TSX"

# --- Output ---
if $SCORE_MODE; then
  if [[ $TOTAL_INTERACTIVE -eq 0 ]]; then
    SCORE="1.0"
  else
    SCORE=$(awk "BEGIN { s = 1 - ($VIOLATION_COUNT / $TOTAL_INTERACTIVE); if (s < 0) s = 0; printf \"%.2f\", s }")
  fi
  DETAILS="Found ${VIOLATION_COUNT} violation(s) out of ${TOTAL_INTERACTIVE} interactive element(s)."
  DETAILS_ESC=$(printf '%s' "$DETAILS" | sed 's/\\/\\\\/g; s/"/\\"/g')
  echo "{\"score\": ${SCORE}, \"details\": \"${DETAILS_ESC}\"}"
  if [[ $VIOLATION_COUNT -gt 0 ]]; then
    exit 1
  fi
  exit 0
fi

if [[ $VIOLATION_COUNT -gt 0 ]]; then
  echo "FAIL: ${VIOLATION_COUNT} component abstraction violation(s) found."
  echo ""
  echo "Violations:"
  echo -e "$VIOLATIONS"
  echo ""
  echo "Fix: Use wrapper components from the project's component library instead of raw elements."
  if [[ -n "$COMPONENT_LIB_DIR" ]]; then
    echo "  Component library: ${COMPONENT_LIB_DIR}/"
  fi
  if [[ -n "$PRIMITIVE_LIB" ]]; then
    echo "  Do not import directly from ${PRIMITIVE_LIB}/*."
  fi
  echo "  The wrapper components add design tokens, accessibility defaults, and consistent API surfaces."
  exit 1
else
  echo "PASS: All interactive elements use design system components."
  exit 0
fi
