#!/usr/bin/env bash
set -euo pipefail

# check-font-family.sh
# ---------------------
# Ensures changed files only use approved font families as defined in
# the project's design baseline.
#
# Rules are derived from .factory/design-system/design-baseline.json
# (generated by the auditor agent at runtime). If the baseline does not
# exist, the check exits neutral (score 1.0, exit 0).
#
# Catches:
#   - font-family: declarations in CSS
#   - fontFamily: or fontFamily= in TSX/TS
#   - font-['...'] Tailwind arbitrary font classes
#
# Exit 0 = pass, Exit 1 = fail
# Use --score to get JSON output for eval integration.

SCORE_MODE=false
if [[ "${1:-}" == "--score" ]]; then
  SCORE_MODE=true
fi

BASELINE=".factory/design-system/design-baseline.json"

# --- Load baseline or exit neutral ---
if [[ ! -f "$BASELINE" ]]; then
  if $SCORE_MODE; then
    echo '{"score": 1.0, "details": "No design-baseline.json found. Skipping font family check (neutral)."}'
  else
    echo "NEUTRAL: No design-baseline.json found. Skipping font family check."
  fi
  exit 0
fi

# --- Extract approved font families from baseline ---
# The baseline has token_registry.typography.font_families with keys like
# "sans", "display", "mono" whose values are the font family names.
# Extract all font family name values from the font_families object.
APPROVED_FONTS_RAW=$(grep -A 20 '"font_families"' "$BASELINE" 2>/dev/null \
  | grep -oE '"(sans|display|mono|serif|heading|body|code)"\s*:\s*"[^"]*"' 2>/dev/null \
  | sed -E 's/.*:\s*"([^"]*)"/\1/' \
  | tr '[:upper:]' '[:lower:]' || true)

if [[ -z "$APPROVED_FONTS_RAW" ]]; then
  if $SCORE_MODE; then
    echo '{"score": 1.0, "details": "No font families defined in baseline. Skipping font check (neutral)."}'
  else
    echo "NEUTRAL: No font families defined in design-baseline.json. Skipping."
  fi
  exit 0
fi

# Build a pipe-separated pattern from discovered font families
APPROVED_FONTS=$(echo "$APPROVED_FONTS_RAW" | sed 's/[.[\*^$()+?{}|]/\\&/g' | paste -sd '|' -)

# Also allow generic CSS keywords and common system fallbacks
APPROVED_GENERIC="inherit|initial|unset|sans-serif|serif|monospace|cursive|fantasy|system-ui|ui-sans-serif|ui-serif|ui-monospace|ui-rounded"

# --- Gather files to check ---
if [[ "${SCAN_MODE:-}" == "full" ]]; then
  CHANGED=$(find "${SCAN_SRC_DIR:-src}" -type f \( -name '*.tsx' -o -name '*.ts' -o -name '*.css' \) 2>/dev/null | sort || true)
else
  CHANGED_FILES=$(git diff --name-only HEAD~1 2>/dev/null || true)
  CHANGED=$(echo "$CHANGED_FILES" | grep -E '\.(tsx|ts|css)$' || true)
fi

if [[ -z "$CHANGED" ]]; then
  if $SCORE_MODE; then
    echo '{"score": 1.0, "details": "No changed files to check."}'
  else
    echo "PASS: No changed .tsx/.ts/.css files to check."
  fi
  exit 0
fi

VIOLATIONS=""
VIOLATION_COUNT=0

while IFS= read -r file; do
  [[ -z "$file" ]] && continue
  [[ ! -f "$file" ]] && continue

  LINE_NUM=0
  while IFS= read -r line; do
    LINE_NUM=$((LINE_NUM + 1))
    FOUND_VIOLATION=false

    # Pattern 1: font-family: in CSS
    if echo "$line" | grep -qiE 'font-family\s*:'; then
      # Extract the value after font-family:
      VALUE=$(echo "$line" | sed -E 's/.*font-family\s*:\s*//I' | sed 's/;.*//' | sed 's/!important//')
      # Split by comma and check each family
      IFS=',' read -ra FAMILIES <<< "$VALUE"
      for family in "${FAMILIES[@]}"; do
        # Trim whitespace and quotes
        clean=$(echo "$family" | sed -E "s/^[[:space:]]*['\"]?//;s/['\"]?[[:space:]]*$//")
        lower=$(echo "$clean" | tr '[:upper:]' '[:lower:]')
        [[ -z "$lower" ]] && continue
        if ! echo "$lower" | grep -qE "^(${APPROVED_FONTS}|${APPROVED_GENERIC})$"; then
          FOUND_VIOLATION=true
        fi
      done
    fi

    # Pattern 2: fontFamily: or fontFamily= in TSX/TS (inline styles)
    if echo "$line" | grep -qE 'fontFamily\s*[:=]'; then
      # Extract the value
      VALUE=$(echo "$line" | sed -E 's/.*fontFamily\s*[:=]\s*//' | sed -E "s/[,}].*//" | sed -E "s/^['\"]//;s/['\"]$//")
      IFS=',' read -ra FAMILIES <<< "$VALUE"
      for family in "${FAMILIES[@]}"; do
        clean=$(echo "$family" | sed -E "s/^[[:space:]]*['\"]?//;s/['\"]?[[:space:]]*$//")
        lower=$(echo "$clean" | tr '[:upper:]' '[:lower:]')
        [[ -z "$lower" ]] && continue
        if ! echo "$lower" | grep -qE "^(${APPROVED_FONTS}|${APPROVED_GENERIC})$"; then
          FOUND_VIOLATION=true
        fi
      done
    fi

    # Pattern 3: font-['...'] Tailwind arbitrary font class
    if echo "$line" | grep -qE "font-\['" ; then
      MATCHES=$(echo "$line" | grep -oE "font-\['[^']+'\]" || true)
      while IFS= read -r match; do
        [[ -z "$match" ]] && continue
        # Extract font name from font-['Font Name']
        FONT_NAME=$(echo "$match" | sed -E "s/font-\['//;s/'\]//;s/_/ /g")
        lower=$(echo "$FONT_NAME" | tr '[:upper:]' '[:lower:]')
        if ! echo "$lower" | grep -qE "^(${APPROVED_FONTS}|${APPROVED_GENERIC})$"; then
          FOUND_VIOLATION=true
        fi
      done <<< "$MATCHES"
    fi

    if $FOUND_VIOLATION; then
      VIOLATION_COUNT=$((VIOLATION_COUNT + 1))
      VIOLATIONS="${VIOLATIONS}  ${file}:${LINE_NUM}  $(echo "$line" | sed 's/^[[:space:]]*//' | head -c 120)\n"
    fi
  done < "$file"
done <<< "$CHANGED"

# --- Output ---
if $SCORE_MODE; then
  if [[ $VIOLATION_COUNT -eq 0 ]]; then
    SCORE="1.0"
  else
    SCORE="0.0"
  fi
  DETAILS="Found ${VIOLATION_COUNT} unapproved font-family declaration(s)."
  DETAILS_ESC=$(printf '%s' "$DETAILS" | sed 's/\\/\\\\/g; s/"/\\"/g')
  echo "{\"score\": ${SCORE}, \"details\": \"${DETAILS_ESC}\"}"
  if [[ $VIOLATION_COUNT -gt 0 ]]; then
    exit 1
  fi
  exit 0
fi

if [[ $VIOLATION_COUNT -gt 0 ]]; then
  echo "FAIL: ${VIOLATION_COUNT} unapproved font-family declaration(s) found."
  echo ""
  echo "Violations:"
  echo -e "$VIOLATIONS"
  echo ""
  echo "Approved font families (from design baseline):"
  echo "$APPROVED_FONTS_RAW" | while IFS= read -r font; do
    echo "  - \"${font}\""
  done
  echo ""
  echo "Fix: Replace the font-family with one of the approved families above."
  echo "Use the Tailwind font classes configured in the project's tailwind.config."
  exit 1
else
  echo "PASS: All font-family declarations use approved fonts."
  exit 0
fi
