#!/usr/bin/env bash
set -euo pipefail

# check-token-purity.sh
# ---------------------
# Ensures changed files use only design-token colors from the project's
# design baseline. Catches hardcoded hex values in Tailwind bracket notation
# (bg-[#abc123], etc.) and compares them against the allowlist.
#
# Rules are derived from .factory/design-system/design-baseline.json
# (generated by the auditor agent at runtime). If the baseline does not
# exist, the check exits neutral (score 1.0, exit 0).
#
# Exit 0 = pass, Exit 1 = fail
# Use --score to get JSON output for eval integration.

SCORE_MODE=false
if [[ "${1:-}" == "--score" ]]; then
  SCORE_MODE=true
fi

BASELINE=".factory/design-system/design-baseline.json"

# --- Load baseline or exit neutral ---
if [[ ! -f "$BASELINE" ]]; then
  if $SCORE_MODE; then
    echo '{"score": 1.0, "details": "No design-baseline.json found. Skipping token purity check (neutral)."}'
  else
    echo "NEUTRAL: No design-baseline.json found. Skipping token purity check."
  fi
  exit 0
fi

# --- Gather files to check ---
if [[ "${SCAN_MODE:-}" == "full" ]]; then
  CHANGED_TSX_TS=$(find "${SCAN_SRC_DIR:-src}" -type f \( -name '*.tsx' -o -name '*.ts' \) 2>/dev/null | sort || true)
else
  CHANGED_FILES=$(git diff --name-only HEAD~1 2>/dev/null || true)
  CHANGED_TSX_TS=$(echo "$CHANGED_FILES" | grep -E '\.(tsx|ts)$' || true)
fi

if [[ -z "$CHANGED_TSX_TS" ]]; then
  if $SCORE_MODE; then
    echo '{"score": 1.0, "details": "No changed .tsx/.ts files to check."}'
  else
    echo "PASS: No changed .tsx/.ts files to check."
  fi
  exit 0
fi

# --- Build allowlist from design-baseline.json ---
# Extract allowed_hex_values from the baseline JSON using grep/sed
# The baseline has: "allowed_hex_values": ["#...", "#...", ...]
ALLOWLIST=$(grep -oE '"#[0-9a-fA-F]{3,8}"' "$BASELINE" 2>/dev/null \
  | sed 's/"//g' \
  | tr '[:upper:]' '[:lower:]' \
  | sort -u || true)

# If the baseline exists but has no hex values, also try extracting from the
# project's CSS file. Look for a css_file path in the baseline, or fall back
# to common locations.
if [[ -z "$ALLOWLIST" ]]; then
  CSS_FILE=""
  # Try to read css_file from baseline
  CSS_FILE=$(grep -oE '"css_file"\s*:\s*"[^"]*"' "$BASELINE" 2>/dev/null \
    | sed -E 's/"css_file"\s*:\s*"//;s/"$//' || true)

  # Fall back to common locations
  if [[ -z "$CSS_FILE" ]] || [[ ! -f "$CSS_FILE" ]]; then
    for candidate in src/index.css src/styles/globals.css src/app/globals.css styles/globals.css; do
      if [[ -f "$candidate" ]]; then
        CSS_FILE="$candidate"
        break
      fi
    done
  fi

  if [[ -n "$CSS_FILE" ]] && [[ -f "$CSS_FILE" ]]; then
    ALLOWLIST=$(grep -oE '--color-[^:]+:\s*#[0-9a-fA-F]{3,8}' "$CSS_FILE" 2>/dev/null \
      | grep -oE '#[0-9a-fA-F]{3,8}' \
      | tr '[:upper:]' '[:lower:]' \
      | sort -u || true)
  fi
fi

# --- Scan for hardcoded hex in Tailwind bracket notation ---
# Patterns: bg-[#, text-[#, border-[#, shadow-[#, ring-[#, from-[#, to-[#,
#           via-[#, outline-[#, fill-[#, stroke-[#, decoration-[#,
#           placeholder-[#, caret-[#, accent-[#
HEX_PATTERN='(bg|text|border|shadow|ring|from|to|via|outline|fill|stroke|decoration|placeholder|caret|accent)-\[#[0-9a-fA-F]{3,8}\]'

VIOLATIONS=""
VIOLATION_COUNT=0
TOTAL_COLOR_REFS=0

while IFS= read -r file; do
  [[ -z "$file" ]] && continue
  [[ ! -f "$file" ]] && continue

  LINE_NUM=0
  while IFS= read -r line; do
    LINE_NUM=$((LINE_NUM + 1))

    # Find all hex bracket notation matches on this line
    MATCHES=$(echo "$line" | grep -oE "$HEX_PATTERN" 2>/dev/null || true)
    if [[ -n "$MATCHES" ]]; then
      while IFS= read -r match; do
        [[ -z "$match" ]] && continue
        TOTAL_COLOR_REFS=$((TOTAL_COLOR_REFS + 1))

        # Extract the hex value and normalize
        HEX=$(echo "$match" | grep -oE '#[0-9a-fA-F]{3,8}' | tr '[:upper:]' '[:lower:]')

        # Check against allowlist
        if [[ -n "$ALLOWLIST" ]] && echo "$ALLOWLIST" | grep -qF "$HEX"; then
          continue
        fi

        VIOLATION_COUNT=$((VIOLATION_COUNT + 1))
        VIOLATIONS="${VIOLATIONS}  ${file}:${LINE_NUM}  ${match}  (hex ${HEX} is not a design token)\n"
      done <<< "$MATCHES"
    fi
  done < "$file"
done <<< "$CHANGED_TSX_TS"

# --- Output ---
if $SCORE_MODE; then
  if [[ $TOTAL_COLOR_REFS -eq 0 ]]; then
    SCORE="1.0"
  else
    # score = max(0, 1 - violations/total)
    SCORE=$(awk "BEGIN { s = 1 - ($VIOLATION_COUNT / $TOTAL_COLOR_REFS); if (s < 0) s = 0; printf \"%.2f\", s }")
  fi
  DETAILS="Found ${VIOLATION_COUNT} violation(s) out of ${TOTAL_COLOR_REFS} color reference(s)."
  DETAILS_ESC=$(printf '%s' "$DETAILS" | sed 's/\\/\\\\/g; s/"/\\"/g')
  echo "{\"score\": ${SCORE}, \"details\": \"${DETAILS_ESC}\"}"
  if [[ $VIOLATION_COUNT -gt 0 ]]; then
    exit 1
  fi
  exit 0
fi

if [[ $VIOLATION_COUNT -gt 0 ]]; then
  echo "FAIL: ${VIOLATION_COUNT} hardcoded hex color(s) not in design tokens."
  echo ""
  echo "Violations:"
  echo -e "$VIOLATIONS"
  echo ""
  echo "Fix: Replace hardcoded hex values with Tailwind classes that reference"
  echo "design tokens. Allowed hex values are defined in the design baseline"
  echo "(.factory/design-system/design-baseline.json) or the project's CSS custom properties."
  exit 1
else
  echo "PASS: All ${TOTAL_COLOR_REFS} color reference(s) use design tokens."
  exit 0
fi
