#!/usr/bin/env bash
set -euo pipefail

# check-patterns.sh
# -----------------
# Ensures new code follows established project conventions as defined in
# the project's design baseline.
#
# Rules are derived from .factory/design-system/design-baseline.json
# (generated by the auditor agent at runtime). If the baseline does not
# exist, the check exits neutral (score 1.0, exit 0).
#
# Reads from the baseline:
#   - pattern_library.page_structure.page_glob (e.g., "src/features/*/page.tsx")
#   - pattern_library.page_structure.required_component (e.g., "PageHeader")
#   - pattern_library.page_structure.required_import (e.g., "@/components/page-header")
#   - component_inventory.component_library_dir (e.g., "src/components/ui")
#
# If pattern_library is not available, skips pattern checks and returns neutral.
#
# Shared component naming conventions (kebab-case filename -> PascalCase export)
# are checked when component_library_dir is known, using the parent directory
# of the component library (e.g., src/components/*.tsx excluding ui/).
#
# Exit 0 = pass, Exit 1 = fail
# Use --score to get JSON output for eval integration.

SCORE_MODE=false
if [[ "${1:-}" == "--score" ]]; then
  SCORE_MODE=true
fi

BASELINE=".factory/design-system/design-baseline.json"

# --- Load baseline or exit neutral ---
if [[ ! -f "$BASELINE" ]]; then
  if $SCORE_MODE; then
    echo '{"score": 1.0, "details": "No design-baseline.json found. Skipping pattern checks (neutral)."}'
  else
    echo "NEUTRAL: No design-baseline.json found. Skipping pattern checks."
  fi
  exit 0
fi

# --- Extract pattern configuration from baseline ---
# Page structure: glob pattern for page files
PAGE_GLOB=$(grep -oE '"page_glob"\s*:\s*"[^"]*"' "$BASELINE" 2>/dev/null \
  | sed -E 's/"page_glob"\s*:\s*"//;s/"$//' || true)

# Page structure: required component name (e.g., "PageHeader")
REQUIRED_COMPONENT=$(grep -oE '"required_component"\s*:\s*"[^"]*"' "$BASELINE" 2>/dev/null \
  | sed -E 's/"required_component"\s*:\s*"//;s/"$//' || true)

# Page structure: required import path (e.g., "@/components/page-header")
REQUIRED_IMPORT=$(grep -oE '"required_import"\s*:\s*"[^"]*"' "$BASELINE" 2>/dev/null \
  | sed -E 's/"required_import"\s*:\s*"//;s/"$//' || true)

# Component library directory
COMPONENT_LIB_DIR=$(grep -oE '"component_library_dir"\s*:\s*"[^"]*"' "$BASELINE" 2>/dev/null \
  | sed -E 's/"component_library_dir"\s*:\s*"//;s/"$//' || true)

HAS_PAGE_PATTERNS=false
if [[ -n "$PAGE_GLOB" ]] && [[ -n "$REQUIRED_COMPONENT" ]]; then
  HAS_PAGE_PATTERNS=true
fi

HAS_COMPONENT_PATTERNS=false
if [[ -n "$COMPONENT_LIB_DIR" ]]; then
  # Derive shared components dir from the component library dir
  # e.g., "src/components/ui" -> shared components are "src/components/*.tsx"
  SHARED_COMPONENTS_DIR=$(dirname "$COMPONENT_LIB_DIR")
  if [[ -n "$SHARED_COMPONENTS_DIR" ]] && [[ "$SHARED_COMPONENTS_DIR" != "." ]]; then
    HAS_COMPONENT_PATTERNS=true
  fi
fi

if ! $HAS_PAGE_PATTERNS && ! $HAS_COMPONENT_PATTERNS; then
  if $SCORE_MODE; then
    echo '{"score": 1.0, "details": "No pattern rules defined in baseline. Skipping (neutral)."}'
  else
    echo "NEUTRAL: No pattern rules defined in design-baseline.json. Skipping."
  fi
  exit 0
fi

# --- Gather files to check ---
if [[ "${SCAN_MODE:-}" == "full" ]]; then
  CHANGED_TSX=$(find "${SCAN_SRC_DIR:-src}" -type f -name '*.tsx' 2>/dev/null | sort || true)
else
  CHANGED_FILES=$(git diff --name-only HEAD~1 2>/dev/null || true)
  CHANGED_TSX=$(echo "$CHANGED_FILES" | grep -E '\.tsx$' || true)
fi

if [[ -z "$CHANGED_TSX" ]]; then
  if $SCORE_MODE; then
    echo '{"score": 1.0, "details": "No changed .tsx files to check."}'
  else
    echo "PASS: No changed .tsx files to check."
  fi
  exit 0
fi

VIOLATIONS=""
VIOLATION_COUNT=0
TOTAL_CHECKS=0

# -----------------------------------------------------------
# Helper: Convert kebab-case filename to PascalCase
# e.g., "data-table" -> "DataTable"
#        "page-header" -> "PageHeader"
# -----------------------------------------------------------
kebab_to_pascal() {
  local input="$1"
  echo "$input" | sed -E 's/(^|-)([a-z])/\U\2/g'
}

# -----------------------------------------------------------
# Check (a): Page components must use the required component
# -----------------------------------------------------------
if $HAS_PAGE_PATTERNS; then
  # Convert glob pattern to grep regex for matching file paths
  # e.g., "src/features/*/page.tsx" -> "src/features/[^/]+/page\.tsx"
  PAGE_REGEX=$(echo "$PAGE_GLOB" | sed -E 's/\./\\./g; s/\*\*/[^ ]*/g; s/\*/[^\/]+/g')
  PAGE_FILES=$(echo "$CHANGED_TSX" | grep -E "${PAGE_REGEX}$" || true)

  if [[ -n "$PAGE_FILES" ]]; then
    while IFS= read -r file; do
      [[ -z "$file" ]] && continue
      [[ ! -f "$file" ]] && continue
      TOTAL_CHECKS=$((TOTAL_CHECKS + 1))

      # Check for required component import or usage
      HAS_REQUIRED=false
      SEARCH_PATTERNS="${REQUIRED_COMPONENT}"
      if [[ -n "$REQUIRED_IMPORT" ]]; then
        SEARCH_PATTERNS="${SEARCH_PATTERNS}|${REQUIRED_IMPORT}"
      fi
      if grep -qE "(${SEARCH_PATTERNS})" "$file" 2>/dev/null; then
        HAS_REQUIRED=true
      fi

      if ! $HAS_REQUIRED; then
        VIOLATION_COUNT=$((VIOLATION_COUNT + 1))
        VIOLATIONS="${VIOLATIONS}  ${file}  Page component missing ${REQUIRED_COMPONENT}\n"
        if [[ -n "$REQUIRED_IMPORT" ]]; then
          VIOLATIONS="${VIOLATIONS}    Expected import from \"${REQUIRED_IMPORT}\"\n"
        fi
      fi

      # Check feature module structure: if the page has significant code,
      # related components should be in a components/ subdir
      FEATURE_DIR=$(dirname "$file")
      JSX_LINES=$(grep -cE '<[A-Z]' "$file" 2>/dev/null || echo "0")

      if [[ $JSX_LINES -gt 20 ]]; then
        if [[ ! -d "${FEATURE_DIR}/components" ]]; then
          LOCAL_COMPONENTS=$(grep -cE '^(export )?(function|const) [A-Z][a-zA-Z]+' "$file" 2>/dev/null || echo "0")
          if [[ $LOCAL_COMPONENTS -gt 2 ]]; then
            TOTAL_CHECKS=$((TOTAL_CHECKS + 1))
            VIOLATION_COUNT=$((VIOLATION_COUNT + 1))
            VIOLATIONS="${VIOLATIONS}  ${file}  ${LOCAL_COMPONENTS} component(s) defined inline in page file\n"
            VIOLATIONS="${VIOLATIONS}    Consider extracting to ${FEATURE_DIR}/components/\n"
          fi
        fi
      fi
    done <<< "$PAGE_FILES"
  fi
fi

# -----------------------------------------------------------
# Check (b): Shared components must export matching PascalCase name
# -----------------------------------------------------------
if $HAS_COMPONENT_PATTERNS; then
  # Match files directly in the shared components dir, excluding the ui/ subdir
  COMPONENT_LIB_BASENAME=$(basename "$COMPONENT_LIB_DIR")
  SHARED_COMPONENTS=$(echo "$CHANGED_TSX" | grep -E "^${SHARED_COMPONENTS_DIR}/[^/]+\.tsx$" | grep -v "${COMPONENT_LIB_DIR}/" || true)

  if [[ -n "$SHARED_COMPONENTS" ]]; then
    while IFS= read -r file; do
      [[ -z "$file" ]] && continue
      [[ ! -f "$file" ]] && continue
      TOTAL_CHECKS=$((TOTAL_CHECKS + 1))

      # Get the filename without extension and path
      BASENAME=$(basename "$file" .tsx)

      # Skip index files
      if [[ "$BASENAME" == "index" ]]; then
        continue
      fi

      # Convert kebab-case filename to expected PascalCase
      EXPECTED_NAME=$(kebab_to_pascal "$BASENAME")

      # Check for exported function/const matching the expected name
      HAS_EXPORT=false

      # Pattern 1: export function ComponentName
      if grep -qE "export (default )?function ${EXPECTED_NAME}[^a-zA-Z]" "$file" 2>/dev/null; then
        HAS_EXPORT=true
      fi

      # Pattern 2: export const ComponentName
      if grep -qE "export (default )?const ${EXPECTED_NAME}[^a-zA-Z]" "$file" 2>/dev/null; then
        HAS_EXPORT=true
      fi

      # Pattern 3: export default ComponentName (separate export)
      if grep -qE "export default ${EXPECTED_NAME}[^a-zA-Z]" "$file" 2>/dev/null; then
        HAS_EXPORT=true
      fi

      # Pattern 4: export { ComponentName } or export { Something as ComponentName }
      if grep -qE "export \{[^}]*${EXPECTED_NAME}" "$file" 2>/dev/null; then
        HAS_EXPORT=true
      fi

      # Pattern 5: function defined and then exported
      if grep -qE "(function|const) ${EXPECTED_NAME}[^a-zA-Z]" "$file" 2>/dev/null; then
        if grep -qE "export" "$file" 2>/dev/null; then
          HAS_EXPORT=true
        fi
      fi

      if ! $HAS_EXPORT; then
        VIOLATION_COUNT=$((VIOLATION_COUNT + 1))
        ACTUAL_EXPORTS=$(grep -oE 'export (default )?(function|const) [A-Z][a-zA-Z]*' "$file" 2>/dev/null | head -3 || true)
        VIOLATIONS="${VIOLATIONS}  ${file}  Expected export named \"${EXPECTED_NAME}\" (from filename \"${BASENAME}\")\n"
        if [[ -n "$ACTUAL_EXPORTS" ]]; then
          VIOLATIONS="${VIOLATIONS}    Found exports: $(echo "$ACTUAL_EXPORTS" | tr '\n' ', ')\n"
        fi
        VIOLATIONS="${VIOLATIONS}    Either rename the file or the exported component to match\n"
      fi
    done <<< "$SHARED_COMPONENTS"
  fi
fi

# --- Output ---
if $SCORE_MODE; then
  if [[ $TOTAL_CHECKS -eq 0 ]]; then
    SCORE="1.0"
  else
    PASSED=$((TOTAL_CHECKS - VIOLATION_COUNT))
    SCORE=$(awk "BEGIN { printf \"%.2f\", $PASSED / $TOTAL_CHECKS }")
  fi
  DETAILS="Checked ${TOTAL_CHECKS} pattern(s), ${VIOLATION_COUNT} violation(s)."
  DETAILS_ESC=$(printf '%s' "$DETAILS" | sed 's/\\/\\\\/g; s/"/\\"/g')
  echo "{\"score\": ${SCORE}, \"details\": \"${DETAILS_ESC}\"}"
  if [[ $VIOLATION_COUNT -gt 0 ]]; then
    exit 1
  fi
  exit 0
fi

if [[ $VIOLATION_COUNT -gt 0 ]]; then
  echo "FAIL: ${VIOLATION_COUNT} project pattern violation(s) found."
  echo ""
  echo "Violations:"
  echo -e "$VIOLATIONS"
  echo ""
  echo "Project conventions (from design baseline):"
  if $HAS_PAGE_PATTERNS; then
    echo "  1. Page components (${PAGE_GLOB}) must use <${REQUIRED_COMPONENT}>"
    echo "  2. Complex pages should extract sub-components to a components/ subdir"
  fi
  if $HAS_COMPONENT_PATTERNS; then
    echo "  3. Shared components (${SHARED_COMPONENTS_DIR}/*.tsx) must export a PascalCase name"
    echo "     matching the kebab-case filename (e.g., data-table.tsx -> DataTable)"
  fi
  exit 1
else
  if [[ $TOTAL_CHECKS -eq 0 ]]; then
    echo "PASS: No page or shared component files to check."
  else
    echo "PASS: All ${TOTAL_CHECKS} file(s) follow project patterns."
  fi
  exit 0
fi
